services:
  redis:
    image: registry.ainnovation.com/bg_cto/newagent-redis
    restart: always
    ports:
      - "9339:6379"
    volumes:
      - ../data/redis_data:/data
      - ./backend/services/docker/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: registry.ainnovation.com/bg_cto/newagent-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ../data/rabbitmq_data:/var/lib/rabbitmq
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    image: registry.ainnovation.com/bg_cto/newagent-backend
    restart: always
    platform: linux/amd64
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
    ports:
      - "3457:8000"
    volumes:
      - ./backend/.env:/app/.env:ro
      - ../data/logs:/app/logs
    env_file:
      - ./backend/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_SSL=False
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started

  worker:
    image: registry.ainnovation.com/bg_cto/newagent-backend
    platform: linux/amd64
    restart: always
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
    command: uv run dramatiq --skip-logging --processes 4 --threads 4 run_agent_background
    volumes:
      - ./backend/.env:/app/.env:ro
    env_file:
      - ./backend/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_SSL=False
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  frontend:
    image: registry.ainnovation.com/bg_cto/newagent-frontend
    init: true
    restart: always
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
    ports:
      - "3458:3000"
    volumes:
      - ./frontend/.env.local:/app/.env.local:ro
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"]
    depends_on:
      - backend

  frontend_ori:
    image: registry.ainnovation.com/bg_cto/newagent-frontend-ori
    init: true
    restart: always
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    ports:
      - "3459:3000"
    volumes:
      - ./frontend/.env.local:/app/.env.local:ro
    environment:
      - NODE_ENV=production
    command: [ "npm", "run", "start" ]
    depends_on:
      - backend

volumes:
  redis_data:
  rabbitmq_data:
